/**
 * The 108 countries offered by the contact form, mapped to what GoHighLevel
 * needs from each one.
 *
 * Two consumers, one table:
 *  - `iso2` populates GHL's STANDARD `country` field, which stores ISO-3166
 *    alpha-2 ("PH"), not the display name the form collects ("Philippines").
 *  - `dial` builds an E.164 phone number. GHL rejects bare national numbers
 *    with a blank, unexplained error, so the dialling code is not optional.
 *
 * Keys must stay byte-identical to the `countries` array in
 * components/ContactForm.tsx. A country missing here degrades safely: the
 * contact is still created, without a country and without a phone number.
 */
export interface CountryInfo {
    readonly iso2: string;
    readonly dial: string;
}

export const COUNTRIES: Readonly<Record<string, CountryInfo>> = {
    "Afghanistan": { iso2: "AF", dial: "93" },
    "Albania": { iso2: "AL", dial: "355" },
    "Algeria": { iso2: "DZ", dial: "213" },
    "Argentina": { iso2: "AR", dial: "54" },
    "Australia": { iso2: "AU", dial: "61" },
    "Austria": { iso2: "AT", dial: "43" },
    "Bahamas": { iso2: "BS", dial: "1" },
    "Bahrain": { iso2: "BH", dial: "973" },
    "Bangladesh": { iso2: "BD", dial: "880" },
    "Belgium": { iso2: "BE", dial: "32" },
    "Belize": { iso2: "BZ", dial: "501" },
    "Bolivia": { iso2: "BO", dial: "591" },
    "Brazil": { iso2: "BR", dial: "55" },
    "Brunei": { iso2: "BN", dial: "673" },
    "Bulgaria": { iso2: "BG", dial: "359" },
    "Cambodia": { iso2: "KH", dial: "855" },
    "Canada": { iso2: "CA", dial: "1" },
    "Chile": { iso2: "CL", dial: "56" },
    "China": { iso2: "CN", dial: "86" },
    "Colombia": { iso2: "CO", dial: "57" },
    "Costa Rica": { iso2: "CR", dial: "506" },
    "Croatia": { iso2: "HR", dial: "385" },
    "Cuba": { iso2: "CU", dial: "53" },
    "Cyprus": { iso2: "CY", dial: "357" },
    "Czech Republic": { iso2: "CZ", dial: "420" },
    "Denmark": { iso2: "DK", dial: "45" },
    "Dominican Republic": { iso2: "DO", dial: "1" },
    "Ecuador": { iso2: "EC", dial: "593" },
    "Egypt": { iso2: "EG", dial: "20" },
    "El Salvador": { iso2: "SV", dial: "503" },
    "Estonia": { iso2: "EE", dial: "372" },
    "Ethiopia": { iso2: "ET", dial: "251" },
    "Fiji": { iso2: "FJ", dial: "679" },
    "Finland": { iso2: "FI", dial: "358" },
    "France": { iso2: "FR", dial: "33" },
    "Germany": { iso2: "DE", dial: "49" },
    "Ghana": { iso2: "GH", dial: "233" },
    "Greece": { iso2: "GR", dial: "30" },
    "Guatemala": { iso2: "GT", dial: "502" },
    "Honduras": { iso2: "HN", dial: "504" },
    "Hungary": { iso2: "HU", dial: "36" },
    "Iceland": { iso2: "IS", dial: "354" },
    "India": { iso2: "IN", dial: "91" },
    "Indonesia": { iso2: "ID", dial: "62" },
    "Iran": { iso2: "IR", dial: "98" },
    "Iraq": { iso2: "IQ", dial: "964" },
    "Ireland": { iso2: "IE", dial: "353" },
    "Israel": { iso2: "IL", dial: "972" },
    "Italy": { iso2: "IT", dial: "39" },
    "Jamaica": { iso2: "JM", dial: "1" },
    "Japan": { iso2: "JP", dial: "81" },
    "Jordan": { iso2: "JO", dial: "962" },
    "Kazakhstan": { iso2: "KZ", dial: "7" },
    "Kenya": { iso2: "KE", dial: "254" },
    "Kuwait": { iso2: "KW", dial: "965" },
    "Latvia": { iso2: "LV", dial: "371" },
    "Lebanon": { iso2: "LB", dial: "961" },
    "Lithuania": { iso2: "LT", dial: "370" },
    "Luxembourg": { iso2: "LU", dial: "352" },
    "Madagascar": { iso2: "MG", dial: "261" },
    "Malaysia": { iso2: "MY", dial: "60" },
    "Maldives": { iso2: "MV", dial: "960" },
    "Malta": { iso2: "MT", dial: "356" },
    "Mexico": { iso2: "MX", dial: "52" },
    "Monaco": { iso2: "MC", dial: "377" },
    "Mongolia": { iso2: "MN", dial: "976" },
    "Morocco": { iso2: "MA", dial: "212" },
    "Myanmar": { iso2: "MM", dial: "95" },
    "Nepal": { iso2: "NP", dial: "977" },
    "Netherlands": { iso2: "NL", dial: "31" },
    "New Zealand": { iso2: "NZ", dial: "64" },
    "Nicaragua": { iso2: "NI", dial: "505" },
    "Nigeria": { iso2: "NG", dial: "234" },
    "North Korea": { iso2: "KP", dial: "850" },
    "Norway": { iso2: "NO", dial: "47" },
    "Oman": { iso2: "OM", dial: "968" },
    "Pakistan": { iso2: "PK", dial: "92" },
    "Panama": { iso2: "PA", dial: "507" },
    "Paraguay": { iso2: "PY", dial: "595" },
    "Peru": { iso2: "PE", dial: "51" },
    "Philippines": { iso2: "PH", dial: "63" },
    "Poland": { iso2: "PL", dial: "48" },
    "Portugal": { iso2: "PT", dial: "351" },
    "Qatar": { iso2: "QA", dial: "974" },
    "Romania": { iso2: "RO", dial: "40" },
    "Russia": { iso2: "RU", dial: "7" },
    "Saudi Arabia": { iso2: "SA", dial: "966" },
    "Serbia": { iso2: "RS", dial: "381" },
    "Singapore": { iso2: "SG", dial: "65" },
    "Slovakia": { iso2: "SK", dial: "421" },
    "Slovenia": { iso2: "SI", dial: "386" },
    "South Africa": { iso2: "ZA", dial: "27" },
    "South Korea": { iso2: "KR", dial: "82" },
    "Spain": { iso2: "ES", dial: "34" },
    "Sri Lanka": { iso2: "LK", dial: "94" },
    "Sweden": { iso2: "SE", dial: "46" },
    "Switzerland": { iso2: "CH", dial: "41" },
    "Taiwan": { iso2: "TW", dial: "886" },
    "Thailand": { iso2: "TH", dial: "66" },
    "Turkey": { iso2: "TR", dial: "90" },
    "Ukraine": { iso2: "UA", dial: "380" },
    "United Arab Emirates": { iso2: "AE", dial: "971" },
    "United Kingdom": { iso2: "GB", dial: "44" },
    "United States": { iso2: "US", dial: "1" },
    "Uruguay": { iso2: "UY", dial: "598" },
    "Venezuela": { iso2: "VE", dial: "58" },
    "Vietnam": { iso2: "VN", dial: "84" },
    "Zimbabwe": { iso2: "ZW", dial: "263" },
};
